### PR TITLE
Fix custom doc link title issue

### LINKED ISSUE #271: Custom link titles authored with []() syntax for doc links are silently ignored
Custom link titles for doc links are silently ignored.

If I write a doc link with a title like:

```
Check out [this great function](doc:Sloth/eat(_:quantity:)).
```

the rendered output is

```
Check out eat(_:quantity:).
```

We should use the user-provided title, per the original Markdown spec.

### Checklist

- [x] If possible, I've reproduced the issue using the `main` branch of this package.
- [x] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/apple/swift-docc/issues).

### Steps to Reproduce

Author a `doc` link to a symbol or article using a custom title, as described above. Build documentation and notice that in the rendered documentation, the custom title isn't used for the link title.

### Swift-DocC Version Information

**Swift-DocC version:** `5.6`
**Swift Compiler version:** N/A

Radar: rdar://79992417

### PR DESCRIPTION
**Pull request by Kyle-Ye**
Bug/issue #, if applicable: 

Close #271 

## Summary

```
## Overview

Hello

Check out [Hi](https://hi.com)

Check out [this great function](doc:Sloth/eat(_:quantity:))

Check out [this great function ![random image](https://picsum.photos/200)](doc:Sloth/eat(_:quantity:))

- <doc:Sloth/eat(_:quantity:)>
```

Before the PR (current behavior)
image

After the PR (expected behavior)
image

## Dependencies

~apple/swift-markdown#82~
apple/swift-markdown#110

## Testing

See RenderContentCompilerTests.swift

https://github.com/apple/swift/pull/61506

## Checklist

Make sure you check off the following items. If they cannot be completed, provide a reason.

- [x] Added tests
- [x] Ran the `./bin/test` script and it succeeded
- [x] Updated documentation if necessary

### CODE REVIEW

File: Sources/SwiftDocC/Model/Rendering/RenderContentCompiler.swift [hunk 1]
```diff
@@ -130,7 +131,13 @@ struct RenderContentCompiler: MarkupVisitor {
         }
         
         collectedTopicReferences.append(resolved)
-        return [RenderInlineContent.reference(identifier: .init(resolved.absoluteString), isActive: true, overridingTitle: nil, overridingTitleInlineContent: nil)]
+        let linkTitleInlineContent = link.children.reduce(into: [], { result, child in result.append(contentsOf: visit(child))}) as! [RenderInlineContent]
```
Comment (d-ronnqvist) [inline Sources/SwiftDocC/Model/Rendering/RenderContentCompiler.swift:134]: Is this different from `flatMap`?

```suggestion
        let linkTitleInlineContent = link.children.flatMap { visit($0) } as! [RenderInlineContent]
```

```

Comment (Kyle-Ye) [reply Sources/SwiftDocC/Model/Rendering/RenderContentCompiler.swift:134]: I think flatMap is better. (Just copied from Line 91😂)

Comment (Kyle-Ye) [reply Sources/SwiftDocC/Model/Rendering/RenderContentCompiler.swift:134]:
```suggestion
        let linkTitleInlineContent =  link.children.compactMap { visit($0) as? [RenderInlineContent] }
```

Fixed

**Comment by Kyle-Ye** [comment]
@swift-ci please test

**Comment by Kyle-Ye** [comment]
Testing passed here with the Markdown change: https://github.com/apple/swift/pull/61506

File: Sources/SwiftDocC/Model/Rendering/RenderContentCompiler.swift [hunk 2]
```diff
@@ -163,7 +163,22 @@ struct RenderContentCompiler: MarkupVisitor {
             return [RenderInlineContent.text(link.plainText)]
         }
         
-        return [RenderInlineContent.reference(identifier: .init(resolved.absoluteString), isActive: true, overridingTitle: nil, overridingTitleInlineContent: nil)]
+        let linkTitleInlineContent = link.children.flatMap { visit($0) } as! [RenderInlineContent]
+        let plainTextLinkTitle = linkTitleInlineContent.plainText
```
Comment (franklinsch) [inline Sources/SwiftDocC/Model/Rendering/RenderContentCompiler.swift:167]: By calling `plainText`, I'm guessing we're losing formatting here? For example if you write `[_Title_](…)`, 'Title' won't be rendered in italics. That's a bit unfortunate but can be address as part of a future PR. It would be good to have an issue to track this.

File: Sources/SwiftDocC/Semantics/MarkupReferenceResolver.swift [hunk 3]
```diff
@@ -113,9 +113,13 @@ struct MarkupReferenceResolver: MarkupRewriter {
...
         }
-        var link = link
-        link.destination = resolvedURL.absoluteString
-        return link
+        if link.destination != resolvedURL.absoluteString {
+            var link = link
+            link.destination = resolvedURL.absoluteString
+            return link
+        } else {
+            return link
```
Comment (franklinsch) [inline Sources/SwiftDocC/Semantics/MarkupReferenceResolver.swift:121]: Not sure I understand why this change is needed, can you elaborate?

**Review by franklinsch — COMMENTED** [review]
This is looking really great, thank you @Kyle-Ye!

File: Sources/SwiftDocC/Semantics/MarkupReferenceResolver.swift (hunk 3 above)
Comment (Kyle-Ye) [reply Sources/SwiftDocC/Semantics/MarkupReferenceResolver.swift:121]: Only update the destination when needed. Because when we update link.destination we'll lose the parsedRange.

+1 for this. This seems not be needed anymore for me since we will preserve the parsedRange in https://github.com/apple/swift-markdown/pull/82 or we will find other ways to different `<doc://xx>` and `[]()`

File: Sources/SwiftDocC/Model/Rendering/RenderContentCompiler.swift (hunk 2 above)
Comment (Kyle-Ye) [reply Sources/SwiftDocC/Model/Rendering/RenderContentCompiler.swift:167]: > I'm guessing we're losing formatting here?

Yes, I just conformed it.

> It would be good to have an issue to track this.

When this PR's fix plan is merged, I'll open a new issue to track the remaining issue left.

**Comment by franklinsch** [comment]
@Kyle-Ye is there remaining work for this PR?

**Comment by Kyle-Ye** [comment]
> @Kyle-Ye is there remaining work for this PR?

The implementation is done. But there is some Code Review discussion to be processed.

Could you help give a look at the following thread👇
- https://github.com/apple/swift-docc/pull/376#discussion_r1014233981
- https://github.com/apple/swift-markdown/pull/82#discussion_r1014220649

@franklinsch

File: Sources/SwiftDocC/Semantics/MarkupReferenceResolver.swift (hunk 3 above)
Comment (Kyle-Ye) [reply Sources/SwiftDocC/Semantics/MarkupReferenceResolver.swift:121]: > Only update the destination when needed. Because when we update link.destination we'll lose the parsedRange.
> 
> +1 for this. This seems not be needed anymore for me since we will preserve the parsedRange in [apple/swift-markdown#82](https://github.com/apple/swift-markdown/pull/82) or we will find other ways to different `<doc://xx>` and `[]()`

After reviewing the [CMark Spec](https://github.com/github/cmark-gfm/blob/master/test/spec.txt), I discovered that it does not have any specially treatment for `<doc://xx>` in markdown. Therefore, no modifications are necessary on the markdown side. It's worth noting that the `<xx>` link is simply a syntax for creating links and functions identically to `[xx](xx)`.
```
## Autolinks

[Autolink](@)s are absolute URIs and email addresses inside
`<` and `>`. They are parsed as links, with the URL or email address
as the link label.
```

Comment (Kyle-Ye) [reply Sources/SwiftDocC/Semantics/MarkupReferenceResolver.swift:121]: The issue lies with `swift-docc` side. Using `overridingTitle` directly will result in the same incorrect output for both formats.
```
- [doc:Sloth/eat(_:quantity:)](doc:Sloth/eat(_:quantity:))
- <doc:Sloth/eat(_:quantity:)>
```

For the above

Comment (Kyle-Ye) [reply Sources/SwiftDocC/Semantics/MarkupReferenceResolver.swift:121]: > The issue lies with `swift-docc` side. Using `overridingTitle` directly will result in the same incorrect output for both formats.
> 
> ```
> - [doc:Sloth/eat(_:quantity:)](doc:Sloth/eat(_:quantity:))
> - <doc:Sloth/eat(_:quantity:)>
> ```

Before the PR, for both formats, we'll get `overridingTitle: nil` & `overridingTitleInlineContent: nil` and encode it to the following json for swift-docc-render to consume. 
```
"content": [
    {
        "type": "paragraph",
        "inlineContent": [
            {
                "type": "reference",
                "isActive": true,
                "identifier": "doc://SlothCreator/documentation/SlothCreator/Sloth/eat(_:quantity:)"
            }
        ]
    }
]
```
Then swift-docc-render will use the reference's titleInlineContent
https://github.com/apple/swift-docc-render/blob/eed919f5dcd8993455dea6534f3c051d58e1cfb3/src/components/ContentNode.vue#L429-L430

If we'd like to support [custom title](doc:xx). A breaking change is needed here since `[doc:Sloth/eat(_:quantity:)](doc:Sloth/eat(_:quantity:))` and `<doc:Sloth/eat(_:quantity:)>` is basically identical outside the CMark Parser world.(Unless we hardcode to check the first char is `[` or `<`) 

So after the PR
`<doc:Sloth/eat(_:quantity:)>` will produce the following node json content
```
"content": [
    {
        "type": "paragraph",
        "inlineContent": [
            {
                "type": "reference",
                "isActive": true,
                "identifier": "doc://SlothCreator/documentation/SlothCreator/Sloth/eat(_:quantity:)",
                "overridingTitle": "doc:Sloth/eat(_:quantity:)"
            }
        ]
    }
]
```
and then swift-docc-render will use "doc:Sloth/eat(_:quantity:)" as its title instead of "eat(_:quantity:)".

Comment (Kyle-Ye) [reply Sources/SwiftDocC/Semantics/MarkupReferenceResolver.swift:121]: Hi @franklinsch, I am seeking your assistance with a design decision for the PR. Could you kindly review it and provide your feedback on the proposed changes? Thank you in advance for your help.

1. Both formats will give the same standard overriding output of "`doc:Sloth/eat(_:quantity:)`"
- Pros: Fixing the custom doc link title issue
- Cons: Making `<doc:Sloth/eat(_:quantity:)>` show "`doc:Sloth/eat(_:quantity:)`" instead of "`eat(_:quantity:)`"
```
- [doc:Sloth/eat(_:quantity:)](doc:Sloth/eat(_:quantity:))
- <doc:Sloth/eat(_:quantity:)>
```

2. Do a specially treatment for <doc://>
- Pros: Fixing the custom doc link title issue while maintaining the history behavior for `<doc:Sloth/eat(_:quantity:)>`
- Cons: We are adding strange logic for the CMark Spec and add maintain cost.
  - According to the CMark spec `<doc:Sloth/eat(_:quantity:)>` is just a syntax sugar for `[doc:Sloth/eat(_:quantity:)](doc:Sloth/eat(_:quantity:))`

Comment (franklinsch) [reply Sources/SwiftDocC/Semantics/MarkupReferenceResolver.swift]: thanks for the overview. I would much prefer if we implemented a solution that doesn't break existing behaviour. It seems like Suggestion A would change the way links get rendered.

For suggestion B, is there a way we can isolate the special behaviour to just auto links using the `doc` URL scheme? I'm fine with `<doc:Sloth/eat(_:quantity:)>` getting translated to `[eat(_:quantity:)](doc:Sloth/eat(_:quantity:)`. Turning `doc` links into links whose title is the page's title is one of DocC's features, so this transformation makes sense. You mention adding special logic for the CMark spec; where would these changes be implemented? Swift-Markdown and Swift-DocC?

Comment (Kyle-Ye) [reply Sources/SwiftDocC/Semantics/MarkupReferenceResolver.swift]: Swift-DocC side. And the implementation will look similar to [this](https://github.com/apple/swift-markdown/blob/4cbd46eab22cbeef307095d17958b6ed23b5f38f/Sources/Markdown/Walker/Walkers/MarkupFormatter.swift#L819-L849)

We check the **doc host + autolinks** format - `<doc://>` and assign overridingTitle to nil to match the original behaviour

Comment (Kyle-Ye) [reply Sources/SwiftDocC/Semantics/MarkupReferenceResolver.swift]: I was thinking to add a style property to `Markdown.Link`. But eventually failed to do so since the underlying `cmark-gfm` parser does not give us the extra info. There is only one node type - CMARK_NODE_LINK
```
public struct Link: InlineMarkup, InlineContainer {
    /// The style of the link
    public var style: Style = .normal
    
    public enum Style {
        /// Normal reference link
        ///
        /// For example `[example text](http://example.com)`
        case normal
        /// Doc style link
        ///
        /// For example `<doc://example>`
        case doc
    }
    ...
}
```

> Another implementation we can reference is swift-cmark's [is_autolink](https://github.com/apple/swift-cmark/blob/86aeb491675de6f077a3a6df6cbcac1a25dcbee1/src/commonmark.c#L152-L154)

Comment (franklinsch) [reply Sources/SwiftDocC/Semantics/MarkupReferenceResolver.swift]: Ah I see. If checking if the text of the link matches its destination is a common way of indicating that a link is an auto-link, it makes sense to adopt the same behaviour then. We could expose a computed property on `Markdown.Link`.

Comment (Kyle-Ye) [reply Sources/SwiftDocC/Semantics/MarkupReferenceResolver.swift]: > Gotcha. The check we're doing in Markdown to determine whether a `Link` is an auto link or not seems finicky (`destination == text.string`). If there's a way we can add a property to `Link` that indicates what style of link it is that we can populate during parsing, that would be more robust.

Yes, this check is finicky since it will treat `[doc:Sloth/eat(_:quantity:)](doc:Sloth/eat(_:quantity:))` as an auto-link too. Not respect the user's overriding title "`doc:Sloth/eat(_:quantity:)`".

If we really do not want to break existing behavior. The only solution I came out to diff them is use parsed range to compare "[" and "]" char.
Or the end user of DocC will lose the ability to write a link whose destination is `doc:Sloth/eat(_:quantity:)` and title is `doc:Sloth/eat(_:quantity:)`.(Using the Markdown implementation)

```swift
let source = #"""
<doc://example.com>[doc://example.com](doc://example.com)
"""#
let document = Document(parsing: source, options: [])
print(document.debugDescription())
```
```
Document
└─ Paragraph
   ├─ Link destination: "doc://example.com"
   │  └─ Text "doc://example.com"
   └─ Link destination: "doc://example.com"
      └─ Text "doc://example.com"
```

Comment (Kyle-Ye) [reply Sources/SwiftDocC/Semantics/MarkupReferenceResolver.swift]: > Ah I see. If checking if the text of the link matches its destination is a common way of indicating that a link is an auto-link, it makes sense to adopt the same behaviour then. We could expose a computed property on `Markdown.Link`.

Got it. I'll update to use this approach. The only risk left is the end user of DocC will lose the ability to write a link whose destination is `doc:Sloth/eat(_:quantity:)` and title is `doc:Sloth/eat(_:quantity:)`. 

Since `[doc:Sloth/eat(_:quantity:)](doc:Sloth/eat(_:quantity:))` will be treated as an auto link and the host is `doc`, we'll make the overridingTitle to nil.

Comment (franklinsch) [reply Sources/SwiftDocC/Semantics/MarkupReferenceResolver.swift]: > Got it. I'll update to use this approach. The only risk left is the end user of DocC will lose the ability to write a link whose destination is doc:Sloth/eat(_:quantity:) and title is doc:Sloth/eat(_:quantity:).

I'm not super concerned about this; I don't really see why a user would want to display `doc:Sloth/eat(_:quantity:)` in plain text. In the worst case, they can embed the text in backticks.

**Comment by Kyle-Ye** [comment]
There is still one thing wrong. The _isAutoLink property will get lost after visiting it and visiting back. This issue was identified in the failed test case, `IndexingTests.testTutorial()`.

To address this problem, we can save and restore the original `isAutolink` status when changing a link's destination during a visit to a tutorial. However, this information will still be lost when revisiting that same tutorial. The reason for this is that the link will be generated from `func makeMarkup(_ data: _MarkupData) -> Markup` in `Markup.child(at:)`, and it is not possible to retrieve the original `isAutolink` information at that point.

```
mutating func visitLink(_ link: Link) -> Markup? {
    ...
    let isAutolink = link.isAutolink // save the original isAutolink status
    var link = link
    link.destination = resolvedURL.absoluteString
    link.isAutolink = isAutolink // restore the original isAutolink status
    return link
}
```

File: Sources/SwiftDocC/Model/Rendering/RenderContentCompiler.swift [hunk 4]
```diff
@@ -165,7 +165,18 @@ struct RenderContentCompiler: MarkupVisitor {
...
+        let overridingTitle = plainTextLinkTitle.isEmpty ? nil : plainTextLinkTitle
+        let overridingTitleInlineContent = linkTitleInlineContent.isEmpty ? nil : linkTitleInlineContent
+        return [
+            RenderInlineContent.reference(
+                identifier: .init(resolved.absoluteString),
+                isActive: true,
+                overridingTitle: link.isAutolink ? nil : overridingTitle,
+                overridingTitleInlineContent: link.isAutolink ? nil : overridingTitleInlineContent
+            )
+        ]
```
Comment (Kyle-Ye) [inline Sources/SwiftDocC/Model/Rendering/RenderContentCompiler.swift:179]: A possible solution to fix the failed test case and remove the need of Swift-Markdown's support for `Markdown.Link._isAutolink` property / `Markdown.Link.isAutolink` setter
```suggestion
        let useOverriding: Bool
        if link.isAutolink { // If the link is an auto link, we don't use overriding info
            useOverriding = false
        } else if let overridingTitle,
                  overridingTitle.hasPrefix(DocumentationSchemeHandler.scheme + ":"),
                  destination.hasPrefix(DocumentationSchemeHandler.fullScheme),
                  destination.hasSuffix(overridingTitle.dropFirst((DocumentationSchemeHandler.scheme + ":").count)) { // If the link is a transformed doc link, we don't use overriding info
            useOverriding = false
        } else {
            useOverriding = true
        }
        return [
            RenderInlineContent.reference(
                identifier: .init(resolved.absoluteString),
                isActive: true,
                overridingTitle: useOverriding ? overridingTitle : nil,
                overridingTitleInlineContent: useOverriding ? overridingTitleInlineContent : nil
            )
        ]
```

**Comment by QuietMisdreavus** [comment]
@swift-ci Please tes

**Comment by QuietMisdreavus** [comment]
@swift-ci Please test

**Comment by QuietMisdreavus** [comment]
Looks like the `if let destination` in Swift-Markdown caused an issue. I'll see about getting a PR up.

**Comment by Kyle-Ye** [comment]
@swift-ci please test

**Comment by Kyle-Ye** [comment]
@swift-ci please test

**Comment by Kyle-Ye** [comment]
> Looks like the `if let destination` in Swift-Markdown caused an issue. I'll see about getting a PR up.

The Swift-Markdown is fixed and the test passed on Swift-DocC. Are we ready to merge this? @QuietMisdreavus

**Comment by Kyle-Ye** [comment]
@swift-ci please test
