### PR TITLE
Fix article abstract section issue

### LINKED ISSUE #344: Docc does not deal well with inline <!-- --> comments if they are first after the h1
### Description

Since we cannot add `@Comment` we need to use `<!-- -->` comments in docc markdown files.

Often the first few lines of a docc file under active development may be comment lines, like so:

```md
# ``Example``

<!-- FIXME: update docs when #23232323 is done -->

Provides a nice example...

## Hello world
```

---

The issue is that docc does not understand that the "_first line that is not empty_" actually is `Provides a nice example...` and thus the "subtitle" when referring to ``Example`` from other places, like a:

```

## Topics

### Articles

- <doc:Introduction>
- <doc:Example>
```

results in an empty "subtitle" for the Example:

Screenshot 2022-07-25 at 18 41 03

### Checklist

- [ ] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/apple/swift-docc/issues).

### Expected Behavior

But it should have been:

Screenshot 2022-07-25 at 18 41 53

### Actual behavior

_No response_

### Steps To Reproduce

Explained example situation above

### Swift-DocC Version Information

5.7

### Swift Compiler Version Information

_No response_

### PR DESCRIPTION
**Pull request by Kyle-Ye**
Bug/issue #, if applicable:

## Summary

Close #344  

## Testing

Steps:
1. Create a Swift Package and add documentation2. 
2. In a Article file, add the following text: 
```
# Example

<!--Line a-->

Line b

## Overview

Test
```
3. Compile the package and get the symbol-graph path. 
4. Run `swift-docc preview xx/DemoKit.docc --additional-symbol-graph-dir xx/DemoKit.build/symbol-graph` to see the effect

## Checklist

Make sure you check off the following items. If they cannot be completed, provide a reason.

- [x] Added tests
- [x] Ran the `./bin/test` script and it succeeded
- [x] Updated documentation if necessary

### CODE REVIEW

**Comment by Kyle-Ye** [comment]
@swift-ci please test

File: Tests/SwiftDocCTests/Model/DocumentationMarkupTests.swift [hunk 1]
```diff
@@ -158,6 +158,18 @@ class DocumentationMarkupTests: XCTestCase {
...
+        do {
+            let source = """
+            # Title
+            <!--Line a-->
+            Line b
+            ## Hello, world!
+            Discussion content.
+            """
+            let model = DocumentationMarkup(markup: Document(parsing: source, options: .parseBlockDirectives))
+            XCTAssertNotNil(model.abstractSection)
```
Comment (franklinsch) [inline Tests/SwiftDocCTests/Model/DocumentationMarkupTests.swift:171]: Can we test that the abstract is indeed "Line b" as well? Just to make sure we're not parsing the HTML as the abstract.

**Review by franklinsch — COMMENTED** [review]
Looking great @Kyle-Ye, that was fast! Just a small comment regarding testing

File: Tests/SwiftDocCTests/Model/DocumentationMarkupTests.swift (hunk 1 above)
Comment (Kyle-Ye) [reply Tests/SwiftDocCTests/Model/DocumentationMarkupTests.swift:171]: Nice catch, done

File: Tests/SwiftDocCTests/Model/DocumentationMarkupTests.swift [hunk 2]
```diff
@@ -158,6 +158,22 @@ class DocumentationMarkupTests: XCTestCase {
...
+            Line b
+            ## Hello, world!
+            Discussion content.
+            """
+            let explected = """
+            Text \"Line b\"
+            """
+            let model = DocumentationMarkup(markup: Document(parsing: source, options: .parseBlockDirectives))
+            XCTAssertNotNil(model.abstractSection)
+            XCTAssertEqual(explected, model.abstractSection?.content.map({ $0.detachedFromParent.debugDescription() }).joined(separator: "\n"))
```
Comment (franklinsch) [inline Tests/SwiftDocCTests/Model/DocumentationMarkupTests.swift:175]: Just a small typo here:

```suggestion
            XCTAssertEqual(expected, model.abstractSection?.content.map({ $0.detachedFromParent.debugDescription() }).joined(separator: "\n"))
```

And we don't need the assertion on 174 anymore right? It's covered by the next line?

**Review by franklinsch — APPROVED** [review]

**Comment by Kyle-Ye** [comment]
@swift-ci please test

**Comment by Kyle-Ye** [comment]
@swift-ci please test

File: Tests/SwiftDocCTests/Model/DocumentationMarkupTests.swift [hunk 3]
```diff
@@ -158,6 +158,21 @@ class DocumentationMarkupTests: XCTestCase {
...
+            ## Hello, world!
+            Discussion content.
+            """
+            let expected = """
+            Text \"Line b\"
+            """
+            let model = DocumentationMarkup(markup: Document(parsing: source, options: .parseBlockDirectives))
+            XCTAssertEqual(expected, model.abstractSection?.content.map{ $0.detachedFromParent.debugDescription() }.joined(separator: "\n"))
+        }
     }
```
Comment (ktoso) [inline Tests/SwiftDocCTests/Model/DocumentationMarkupTests.swift:176]: Worth adding an explicit test for the `@Comment{}` as well perhaps?

**Comment by ktoso** [comment]
Looks good, thank you for the quick follow up :) I'd suggest to add another test just to be sure about the @Comment et al.

**Review by ktoso — APPROVED** [review]

File: Tests/SwiftDocCTests/Model/DocumentationMarkupTests.swift (hunk 3 above)
Comment (Kyle-Ye) [reply Tests/SwiftDocCTests/Model/DocumentationMarkupTests.swift:179]: Done. You can check and review the change here [5a4d4](https://github.com/apple/swift-docc/pull/347/commits/5a4d41e2bcdb9ef1b24a79853286c64676df63e2)

**Comment by ktoso** [comment]
Cool thanks!

**Comment by Kyle-Ye** [comment]
@swift-ci please test
