### PR TITLE
Fix duplicated diagnostic issue

### LINKED ISSUE #729: Duplicated diagnostic causing crash on DefaultDiagnosticConsoleFormatter
### Description

See detail on https://github.com/apple/swift-docc/issues/678#issuecomment-1748170163

### Checklist

- [X] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/apple/swift-docc/issues).

### Expected Behavior

Only emit one diagnostic for the actual location - the Extension file.

### Actual behavior

Emit 2 duplicated diagnostic: the Extension Markdown file and the source Swift file

### Steps To Reproduce

Change `eat(_:quantity:)` to `eat(_:quantity:extraLog:)` and build documentation for SlothCreator.

### Swift-DocC Version Information

5.9.0

### Swift Compiler Version Information

```shell
swift-driver version: 1.87.1 Apple Swift version 5.9 (swiftlang-5.9.0.128.108 clang-1500.0.40.1)
Target: arm64-apple-macosx14.0
```

### PR DESCRIPTION
**Pull request by Kyle-Ye**
Bug/issue #, if applicable: 

Close #729 and rdar://79991171

## Summary

If the range’s source is not matched with the resolver’s source, we should not emit a problem

## Dependencies

None

## Testing

See `func testDuplicatedDiagnosticForExtensionFile()` in `MarkupReferenceResolverTests.swift`

## Checklist

Make sure you check off the following items. If they cannot be completed, provide a reason.

- [x] Added tests
- [x] Ran the `./bin/test` script and it succeeded
- [x] Updated documentation if necessary

### CODE REVIEW

**Comment by Kyle-Ye** [comment]
@swift-ci please test

**Comment by Kyle-Ye** [comment]
@swift-ci please test

File: Sources/SwiftDocC/Semantics/MarkupReferenceResolver.swift [hunk 1]
```diff
@@ -80,6 +80,13 @@ struct MarkupReferenceResolver: MarkupRewriter {
             return resolved
             
         case .failure(let unresolved, let error):
+            if let rangeLowerBoundSource = range?.lowerBound.source,
+               let rangeUpperBoundSource = range?.upperBound.source,
+               let source,
```
Comment (d-ronnqvist) [inline Sources/SwiftDocC/Semantics/MarkupReferenceResolver.swift:85]: This `if let` shorthand was added in Swift 5.7 ([SE-0345][1]) but DocC still uses Swift 5.6. 

[1]: https://github.com/apple/swift-evolution/blob/main/proposals/0345-if-let-shorthand.md

```suggestion
               let source = source,
```

File: Tests/SwiftDocCTests/Semantics/MarkupReferenceResolverTests.swift [hunk 2]
```diff
@@ -27,4 +27,11 @@ class MarkupReferenceResolverTests: XCTestCase {
         _ = resolver.visit(document)
         XCTAssertEqual(0, resolver.problems.count)
     }
+
+    func testDuplicatedDiagnosticForExtensionFile() throws {
+        let (_, context) = try testBundleAndContext(named: "ExtensionArticleBundle")
+        // Before #733's change, there will be 2 duplicated problems.
+        // And we'll trigger a index out of range crash in DefaultDiagnosticConsoleFormatter
```
Comment (d-ronnqvist) [inline Tests/SwiftDocCTests/Semantics/MarkupReferenceResolverTests.swift:34]: How about something like this to elaborate on the issue a bit?
```suggestion
        // Before #733, symbols with documentation extension files emitted duplicated problems:
        // - one with a source location in the in-source documentation comment
        // - one with a source location in the documentation extension file.
        // The source range was only valid for one of these diagnostics. This resulted in an index out of range crash in DefaultDiagnosticConsoleFormatter when displaying line that caused the problem to the user
```

File: Tests/SwiftDocCTests/Semantics/MarkupReferenceResolverTests.swift [hunk 3]
```diff
@@ -27,4 +27,11 @@ class MarkupReferenceResolverTests: XCTestCase {
...
+        XCTAssertEqual(1, context.problems.count)
+    }
```
Comment (d-ronnqvist) [inline Tests/SwiftDocCTests/Semantics/MarkupReferenceResolverTests.swift:36]: Should we also verify that this problem comes from the expected source file?
```suggestion
        XCTAssertEqual("Server.md", context.problems.first?.diagnostic.source?.lastPathComponent)
    }
```

**Review by d-ronnqvist — APPROVED** [review]

**Comment by d-ronnqvist** [comment]
This looks good to me. @binamaniar can you take a second look at this while I'm out?

File: Sources/SwiftDocC/Semantics/MarkupReferenceResolver.swift (hunk 1 above)
Comment (Kyle-Ye) [reply Sources/SwiftDocC/Semantics/MarkupReferenceResolver.swift:85]: The Swift 5.7 bump for swift-markdown is discussed in a [workgroup meeting](https://forums.swift.org/t/documentation-workgroup-meeting-july-17th-2023/66170/3). 

Although the inspiration is from swift-markdown, and [the PR](https://github.com/apple/swift-markdown/pull/135) has not been merged for some CR reasons. But according to the SDWG meeting's notes, I think it's OK to bump the version in this PR.

> Kyle: Is it okay to bump the Swift tools version for Swift-Markdown?
> Franklin: Yes, we want to maintain compatibility for folks that haven't had time to update yet, but Swift 5.7 was released a year ago. It's okay for DocC to be using more recent versions since it's primary a toolchain product. 

If you have concerns about this and feel that this bump is not necessary for this PR, we can also update the commit instead.

Comment (d-ronnqvist) [reply Sources/SwiftDocC/Semantics/MarkupReferenceResolver.swift:85]: If we want to cherry-pick this fix into the 5.10 release we probably won't want the Swift bump but it's just one line that'd need to be modified in the cherry-pick PR so it doesn't really matter.

**Comment by Kyle-Ye** [comment]
@swift-ci please test

File: Sources/SwiftDocC/Semantics/MarkupReferenceResolver.swift (hunk 1 above)
Comment (Kyle-Ye) [reply Sources/SwiftDocC/Semantics/MarkupReferenceResolver.swift]: Got it. I'll open a new PR to bump the version instead when needed.

**Comment by Kyle-Ye** [comment]
Ping @binamaniar

**Comment by Kyle-Ye** [comment]
> This looks good to me. @binamaniar can you take a second look at this while I'm out?

@d-ronnqvist I'd like to confirm whether we should wait for binamaniar's approval before the merging.

**Comment by binamaniar** [comment]
sorry for the late reply. Looks good to me to make sure there is no crash when the location is not in source. Just thinking do we need to need an extra check that it is for extension files only. My answer is probably no but sharing my thought process.

**Comment by Kyle-Ye** [comment]
> Just thinking do we need to need an extra check that it is for extension files only.

There is not too much context to get the info(whether it is an extension file) now.
[By checking the extension of the source is "md"? 🤔]

We may consider adding the extra check later if needed. Anyway, thanks for the review suggestion.

**Comment by Kyle-Ye** [comment]
@swift-ci please test
